[project]
name = "demo-chatterbox"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chatterbox-tts>=0.1.1",
    "torchaudio==2.6.0",
]
